version: '3.8'
services:
  
  postgres:
    container_name: postgres
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi

  redis:
    container_name: bbt-template-redis
    image: redis:latest
    ports:
      - '6379:6379'
      
  redisinsight:
    container_name: bbt-template-red-insight
    image: redislabs/redisinsight:latest
    ports:
      - '5501:8001'

