version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.4.0-debian}
    restart: always
    volumes:
      - ./config/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./config/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"

  httpbin:
    image: kennethreitz/httpbin