routes:
  - uri: /hello
    upstream:
      type: roundrobin
      nodes:
        "http://localhost:8180": 1
    plugins:
      openid-connect:
        client_id: apisix-client
        client_secret: R2zSWWwRIy3dvWAPMGfoCCW2XnrrYHnX
        discovery: http://127.0.0.1:8080/realms/apisix/.well-known/openid-configuration
        redirect_uri: http://127.0.0.1:9080/anything/callback
        scope: openid profile
        bearer_only: false
