version: "3.9"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - bbt-development
      
  zeebe:
    image: camunda/zeebe:latest
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elastic:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_REDIS_REMOTE_ADDRESS=redis://redis:6379
      - ZEEBE_REDIS_TIME_TO_LIVE_IN_SECONDS=900
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - ./config/zeebe-config.yaml:/usr/local/zeebe/config/application.yaml
      - ./zeebe-exporters/zeebe-redis-exporter-0.9.2-jar-with-dependencie.jar:/usr/local/zeebe/exporters/zeebe-redis-exporter-jar-with-dependencies.jar
    networks:
      - bbt-development
    depends_on:
      - redis
      
  operate: 
    image: camunda/operate:latest
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment: 
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elastic:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elastic:9200
    networks:
      - bbt-development
    depends_on:
      - zeebe
      - elastic
      
  elastic:
    image: elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - bbt-development
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - bbt-development
    depends_on:
      - elastic
    ports:
      - 5601:5601

networks:
  bbt-development:
    external: true

volumes:
  redis:
  postgres:
  redisinsight: